# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Group all updates into one PR
    groups:
      all-dependencies:
        patterns:
          - "*"
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 1
    # Add assignees
    assignees:
      - "nathanleiby"
    # Add labels
    labels:
      - "npm"
      - "dependencies"
    # Specify the target branch
    target-branch: "master"
    # Set version requirements
    versioning-strategy: auto
    # Allow only security updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
