name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  verify:
    name: Lint, Test, and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint || echo "::warning::Linting issues found, but continuing with build"

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7

      - name: Build
        run: npx vite build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist/
          retention-days: 7

      - name: Check bundle size
        run: |
          echo "Bundle size report:"
          find dist -type f -name "*.js" -o -name "*.css" | xargs ls -lh

      - name: Notify on success
        if: success()
        run: echo "✅ CI checks passed successfully!"
